{
    "description": "Test that global signOut error returns partial success with global sign out error",
    "preConditions": {
        "amplify-configuration": "authconfiguration.json",
        "state": "SignedIn_SessionEstablished.json",
        "mockedResponses": [
            {
                "type": "cognitoIdentityProvider",
                "apiName": "globalSignOut",
                "responseType": "failure",
                "response": {
                    "errorType": "NotAuthorizedException",
                    "errorMessage": null
                }
            }
        ]
    },
    "api": {
        "name": "signOut",
        "params": {
        },
        "options": {
            "globalSignOut": true
        }
    },
    "validations": [
        {
            "type": "amplify",
            "apiName": "signOut",
            "responseType": "complete",
            "response": {
                "globalSignOutError": {
                    "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VySWQiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiZXhwIjoxNTE2MjM5MDIyLCJvcmlnaW5fanRpIjoib3JpZ2luX2p0aSJ9.Xqa-vjJe5wwwsqeRAdHf8kTBn_rYSkDn2lB7xj9Z1xU",
                    "exception": {
                        "errorType": "GlobalSignOutException",
                        "errorMessage": "Failed to sign out globally",
                        "recoverySuggestion": "See attached exception for more details. GlobalSignOut can be retried using the CognitoIdentityProviderClient accessible from the escape hatch.",
                        "cause": {
                            "errorType": "NotAuthorizedException",
                            "errorMessage": null
                        }
                    }
                },
                "hostedUIError": null,
                "revokeTokenError": {
                    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VySWQiLCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiZXhwIjoxNTE2MjM5MDIyLCJvcmlnaW5fanRpIjoib3JpZ2luX2p0aSJ9.Xqa-vjJe5wwwsqeRAdHf8kTBn_rYSkDn2lB7xj9Z1xU",
                    "exception": {
                        "recoverySuggestion": "See attached exception for more details. RevokeToken can be retried using the CognitoIdentityProviderClient accessible from the escape hatch.",
                        "detailMessage": "Failed to revoke token",
                        "cause": {
                            "detailMessage": "RevokeToken not attempted because GlobalSignOut failed.",
                            "stackTrace": [
                            ],
                            "suppressedExceptions": [
                            ]
                        },
                        "stackTrace": [
                        ],
                        "suppressedExceptions": [
                        ]
                    }
                },
                "signedOutLocally": true
            }
        }
    ]
}