{
    "description": "AuthException is thrown when deleteUser API call fails",
    "preConditions": {
        "amplify-configuration": "authconfiguration.json",
        "state": "SignedOut.json",
        "mockedResponses": [
            {
                "type": "cognitoIdentityProvider",
                "apiName": "deleteUser",
                "responseType": "failure",
                "response": {
                    "errorType": "SignedOutException",
                    "errorMessage": null
                }
            }
        ]
    },
    "api": {
        "name": "deleteUser",
        "params": {
        },
        "options": {
        }
    },
    "validations": [
        {
            "type": "amplify",
            "apiName": "deleteUser",
            "responseType": "failure",
            "response": {
                "errorType": "SignedOutException",
                "errorMessage": "Failed since user is not authorized.",
                "recoverySuggestion": "Check whether the given values are correct and the user is authorized to perform the operation.",
                "cause": {
                    "errorType": "SignedOutException",
                    "errorMessage": null
                }
            }
        }
    ]
}