{
  "description": "Test that Passwordless signIn with OTP invokes onError when exception is raised",
  "preConditions": {
    "amplify-configuration": "authconfiguration.json",
    "state": "SignedOut_Configured.json",
    "mockedResponses": [
      {
        "type": "cognitoIdentityProvider",
        "apiName": "initiateAuth",
        "responseType": "failure",
        "response": {
          "errorType": "NotAuthorizedException",
          "errorMessage": "Cognito error message"
        }
      }
    ]
  },
  "api": {
    "name": "signInWithOTP",
    "params": {
      "username": "username",
      "flow": "SIGN_IN",
      "destination": "SMS"
    },
    "options": {
      "signInOptions": {
      }
    }
  },
  "validations": [
    {
      "type": "amplify",
      "apiName": "signInWithOTP",
      "responseType": "failure",
      "response": {
        "errorType": "NotAuthorizedException",
        "errorMessage": "Failed since user is not authorized.",
        "recoverySuggestion": "Check whether the given values are correct and the user is authorized to perform the operation.",
        "cause": {
          "errorType": "NotAuthorizedException",
          "errorMessage": "Cognito error message"
        }
      }
    }
  ]
}